[package]
name = "ref-exchange"
version = "0.2.1"
authors = ["Illia Polosukhin <illia.polosukhin@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "=4.0.0-pre.1", features = ["unstable"] }
near-contract-standards = "=4.0.0-pre.1"
uint = { version = "0.9.0", default-features = false }

[dev-dependencies]
near-sdk-sim = "=4.0.0-pre.1"
test-token = { path = "../test-token" }
